Algoritmo "Lista3, 3"
// Disciplina   : [Lógica de Programação e java script]
// Professor   :Jailson
// Descrição   :Ler dois inteiros (variáveis A e B) e imprimir o resultado do quadrado da diferença do primeiro valor pelo segundo.
// Autor(a)    : Núbia
// Data atual  : 12/09/2022
Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 //a2 + 2ab + b2
 

Fimalgoritmo